/**
 * Starlight route-data middleware (D-0009 P6, generalized in D-0010 P2):
 * injects a roster page's per-entity entries into its "On this page" TOC.
 *
 * Roster pages are tables, not headings, so Starlight's default TOC (built
 * from headings) lists nothing. The table rows carry `<a id>` anchors
 * generated by `sdlc docs generate site`; this middleware maps the generated
 * `tocEntries` (same anchors, same single source — `src/generated/sidebar.mjs`,
 * which also feeds the sidebar's Appendix children) onto TocItems so the
 * right-hand nav lists every entry and click-navigates to its row.
 *
 * `tocEntries` is route-keyed (`{ glossary: [...], references: [...] }`), so a
 * new roster route gets TOC injection by appearing in the map — no per-route
 * branching here ([[D-0010-deterministic-site-assembly]] §3).
 *
 * Known limit: Starlight's scroll-spy highlights TOC entries by nearest
 * *heading*, so table-row entries don't highlight while scrolling —
 * navigation only.
 */
import { defineRouteMiddleware } from '@astrojs/starlight/route-data'
import type { StarlightRouteData } from '@astrojs/starlight/route-data'
import { tocEntries } from './generated/sidebar.mjs'

type TocItems = NonNullable<StarlightRouteData['toc']>['items']

interface AnchorItem {
  label: string
  link: string
}

const tocItems = (items: AnchorItem[]): TocItems =>
  items.map((item) => ({
    depth: 2,
    slug: item.link.split('#')[1] ?? '',
    text: item.label,
    children: [],
  }))

export const onRequest = defineRouteMiddleware((context) => {
  const route = context.locals.starlightRoute
  if (!route?.toc) return
  const id = route.id.replace(/\.(md|mdx)$/, '')
  const items = tocEntries[id]
  if (items) {
    route.toc.items.push(...tocItems(items))
  }
})
